pages:
  script:
    - mkdir public
    - shopt -s extglob  # Enable extended globbing
    - cp -r !(public) public  # Copy everything except the 'public' directory
  artifacts:
    paths:
      - public
  only:
    - master  # Replace 'master' with your default branch name if different